version: '2.1'
services: 
  nocodb: 
    depends_on: 
      root_db: 
        condition: service_healthy
    environment: 
      NC_DB: "pg://root_db:5432?u=${POSTGRES_USER}&p=${POSTGRES_PASSWORD}&d=root_db"
    image: "nocodb/nocodb:latest"
    ports: 
      - "8080:8080"
    restart: always
    volumes: 
      - ${NOCODB_LOCATION}:/usr/app/data
  database:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ${POSTGRES_LOCATION}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "root_db"
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "$${POSTGRES_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 50